AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function deployment template

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: functionfortestingplatformnex
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.17.0
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          abc
      ABC
      Events:
        # HTTP Event
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
        # SNS Event (if configured)
        SnsEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:lambda:eu-north-1:205930628023:function:hello-world-api
        # S3 Event (if configured)
        S3Event:
          Type: S3
          Properties:
            Bucket: 
            Events: 

  # S3 Bucket for deployments
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucketfortestplatformnex